# Generated by Django 2.2.10 on 2020-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0015_auto_20200323_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='_reservation_required',
            field=models.BooleanField(db_column='reservation_required', default=False, help_text='Require that users have a current (within 15 minutes) reservation in order to use the tool'),
        ),
    ]
