# Generated by Django 2.2.10 on 2020-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0017_auto_20200515_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='reservation_warning',
            field=models.PositiveIntegerField(blank=True, help_text='The number of simultaneous reservations allowed in this area before a warning is displayed.', null=True),
        ),
    ]
